-- AlterTable
ALTER TABLE "Person" ADD COLUMN     "bioB" TEXT,
ADD COLUMN     "bioC" TEXT,
ADD COLUMN     "biooA" TEXT,
ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "fieldA" TEXT,
ADD COLUMN     "fieldB" TEXT,
ADD COLUMN     "updatedAt" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP;
